name: "pagely-deploy"
on:
  push:
    branches: [ develop ]
     
jobs:
  deploy:
    name: Deploy to Pagely Staging
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy
        uses: pagely/action-deploy@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_STAGING_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: "niV8Qqt8Af5QjxMnrmXt999"
          PAGELY_APP_ID: "38968"
          PAGELY_WORKING_DIR: ${{github.workspace}}
