name: "WPEngine PRODUCTION Deploy from /production when a pushed to production"
on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check working directory
        working-directory: ${{ github.workspace }}
        run: ls -la
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install root node_modules
        working-directory: wp-content/themes/goldenegg
        run: |
          npm ci
      - name: run gulp for staging
        working-directory: wp-content/themes/goldenegg
        run: |
          npm run gulp:prod
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v2.3.3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          PHP_LINT: TRUE
          CACHE_CLEAR: TRUE

          # Branches & Environments
          PRD_BRANCH: production
          PRD_ENV: goldeneggdev
