name: "Deploy goldenegg /main to WP Engine Production"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:
      
      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }} 
        PHP_LINT: TRUE
        CACHE_CLEAR: TRUE
      
      # Branches & Environments 
        PRD_BRANCH: main
        PRD_ENV: goldeneggdev
