name: "WPEngine Staging Deploy from /develop"
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # spin up a docker container with the latest ubutnu lts running
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: install root node_modules
      # change working-directory to the theme folder path
      working-directory: wp-content/themes/goldenegg
      run: |
        npm ci
    - name: run gulp for staging
      # change working-directory to the theme folder path
      working-directory: wp-content/themes/goldenegg
      run: |
        npm run gulp:stage
    # do not push these files to server
    - name: Remove README.md File
      uses: JesseTG/rm@v1.0.2
      with:
        path: README.md
    - name: Remove Node Modules File
      uses: JesseTG/rm@v1.0.2
      with:
        path: wp-content/themes/goldenegg/node_modules
    # deploy to WP Engine
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        PHP_LINT: FALSE
        CACHE_CLEAR: TRUE

      # Branches & Environments
        STG_BRANCH: develop
        STG_ENV: goldeneggstag
