name: "WP Engine Staging Deploy from /develop"
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Deploy to WP Engine
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        PHP_LINT: FALSE
        CACHE_CLEAR: TRUE

      # Branches & Environments
        STG_BRANCH: develop
        STG_ENV: goldeneggstag
