name: "WP Engine Staging Deploy from /develop"
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THEME_PATH: goldenegg
      DEPLOY_ENV: goldeneggstag
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
        cache-dependency-path: wp-content/themes/${{ env.THEME_PATH }}/package-lock.json
    - name: install root node_modules
      # change working-directory to the theme folder path
      working-directory: wp-content/themes/${{ env.THEME_PATH }}
      run: |
        npm ci
    - name: run gulp for staging
      # change working-directory to the theme folder path
      working-directory: wp-content/themes/${{ env.THEME_PATH }}
      run: |
        npm run gulp:dev
    # remove node_modules like we do in production to catch issues
    - name: remove theme node_modules
      uses: JesseTG/rm@v1.0.2
      with:
        path: wp-content/themes/${{ env.THEME_PATH }}/node_modules

    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        FLAGS: -azvr --inplace --delete --include-from=.deployinclude
        PHP_LINT: FALSE
        CACHE_CLEAR: TRUE

      # Environment
        WPE_ENV: ${{ env.DEPLOY_ENV }}
