name: "WP Engine Staging Deploy from /main when pushed"
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THEME_PATH: goldenegg
      DEPLOY_ENV: goldeneggdev
    steps:
    - uses: actions/checkout@v2

    # spin up a docker container with the latest ubutnu lts running
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
        cache-dependency-path: wp-content/themes/${{ env.THEME_PATH }}/package-lock.json
    - name: install root node_modules
      # change working-directory to the theme folder path
      working-directory: wp-content/themes/goldenegg
      run: |
        npm ci
    - name: run gulp for staging
      # change working-directory to the theme folder path
      working-directory: wp-content/themes/goldenegg
      run: |
        npm run gulp:stage

    # do not push readme or node_modules to server
    - name: remove README.md
      uses: JesseTG/rm@v1.0.2
      with:
        path: README.md
    - name: remove theme node_modules
      uses: JesseTG/rm@v1.0.2
      with:
        path: wp-content/themes/goldenegg/node_modules

    # deploy to WP Engine
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:

      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        PHP_LINT: TRUE
        CACHE_CLEAR: TRUE

      # Environment
        WPE_ENV: ${{ env.DEPLOY_ENV }}
